### ISSUE TITLE
the left comparing window content is always empty 

### ISSUE THREAD

**Issue by bruceman** [CJTozer/SublimeDiffView#41]
Hi,
I have a svn project. i made some changes and use DiffView to check the different.
But the left comparing window content is empty. please see the attachment.

Another issue is :  when i use  diff options, for example "-r 123".  it always show "No changes to report..."

Thanks for your hard work on this wonderful project.

![1](https://cloud.githubusercontent.com/assets/1871738/19616433/63735a54-9845-11e6-9c13-a820f5a4a27a.jpg)

**Comment by bruceman** [comment]
I use macOS serria 10.12 and sublime 3 latest beta version.

**Comment by CJTozer** [comment]
@bruceman thanks for the report.

A few questions to get me started:
* your main problem (with the empty pane as in the screenshot) occurs when you've got no arguments to DiffView correct?  Can you provide the following info:
  * output from `svn --version`, `svn status` and (if it's not sensitive to share) `svn diff`
  * any output from the SublimeText console (View -> Show Console) after you've just run the DIffView command
* has this plugin *ever* worked for you?
* on the second issue - what does `svn diff -r 123` show you?

**Comment by bruceman** [comment]
Thanks for your quick reply, here are the answers.

Q1: svn version:  1.9.4 (r1740329)
svn status: M       test.html
svn diff:
bruce-workstation:dev brli$ svn diff test.html 
Index: test.html
===================================================================
--- test.html	(版本 97694)
+++ test.html	(工作副本)
@@ -6,5 +6,6 @@
 </head>
 <body>
 <h1>test</h1>
+<h2>this is new line</h2>
 </body>
 </html>
\ No newline at end of file

:-(, not any output after run DiffView

Q2: this is my first time to use this plugin.

Q3:
bruce-workstation:dev brli$ svn diff -r 97694 test.html 
Index: test.html
===================================================================
--- test.html	(版本 97694)
+++ test.html	(工作副本)
@@ -6,5 +6,6 @@
 </head>
 <body>
 <h1>test</h1>
+<h2>this is new line</h2>
 </body>
 </html>
\ No newline at end of file

**Comment by CJTozer** [comment]
Ah - well that makes me wonder if the Chinese characters are the problem - I'll try to add a test for this to find out.

**Comment by bruceman** [comment]
@CJTozer thanks, hope to fix this issue.

**Comment by CJTozer** [comment]
Ok so with a new test I don't think it's anything to do with the characters.

Since it's only the left (old) file that's broken, I suspect there may be a problem with the temporary file that DiffView uses to store the old version of the file.  Can you check a couple of things:
* output in your project from `svn cat -r HEAD test.html` (and `svn cat -r 97694 test.html` also since that didn't work either)
* in the SublimeText console, run:
```python
import tempfile
t = tempfile.mkdtemp()
print t
```
* when you have the path being used by `mkdtemp()`, that's going to be the same as is used by DiffView (but with a different unique ID) - can you run the DiffView diff again, and see what new directory is created - and let me know the contents.

Please let me know if you need any more explanation here!

**Comment by bruceman** [comment]
@CJTozer here are the test screenshots
![test-1](https://cloud.githubusercontent.com/assets/1871738/19625628/4410a246-9950-11e6-9e7a-ff2e2048fddc.jpg)
![test-2](https://cloud.githubusercontent.com/assets/1871738/19625629/443698ca-9950-11e6-85f1-8d98100457e4.jpg)

**Comment by CJTozer** [comment]
Sorry that's my bad - forgot we're in Python 3 world - please replace `print t` with `print(t)` in the console example above.

**Comment by bruceman** [comment]
it works, output is :
/var/folders/kn/0skk6hbd00g7wj57dw39j7b00000gn/T/tmpofdg9w

**Comment by bruceman** [comment]
Here are the temp data.
![test-3](https://cloud.githubusercontent.com/assets/1871738/19625763/dc98f42a-9953-11e6-866e-92e5ddde4db8.jpg)

**Comment by bruceman** [comment]
@CJTozer any update on this issue?

**Comment by CJTozer** [comment]
OK I've just released v1.1.1, which should enable us to get more useful info.

This might take a while to permeate through PackageControl, but you should be able to see when you've got the latest version using the `Package Control: List Packages` command - DiffView should be on v1.1.1 (may require Sublime restart to pick up).

Once you're on v1.1.1, add the setting `debug: true` to the DiffView user settings (`Preferences -> Package Settings -> DiffView -> Settings - User`.

Then re-run your failing diff, and let me have the output from ST console.  (Note that you should be able to copy-paste from the ST console, rather than posting screenshots, which would make it easier for me to handle).

Thanks.

**Comment by CJTozer** [comment]
closing as it's very stale - please re-open if you see this and have the diags requested...
