### ISSUE TITLE
Invoking with diff with two files

### ISSUE THREAD

**Issue by mcrajah** [CJTozer/SublimeDiffView#47]
I am not using any of the supported VCS. I use P4. I want to invoke diff by passing two file to diffview using my custom p4 plugin. I would like to invoke diffview using run_command(). 

My files to diff are in a list with full path, but the run_command needs a map. How should I construct the map so that something like this will work. 

window.run_command('diff_view', file_map)?

Thanks

**Comment by CJTozer** [comment]
So, two quick points to answer your question:

* Sublime's `window.run_command` takes a dictionary which is translated to named parameters in the plugin's entry function itself.  For example `view.run_command("goto_line", {"line": 10})` passes `line = 10` to the plugin.  See [here](http://docs.sublimetext.info/en/latest/reference/plugins.html) for more details
* Second, I'm afraid this isn't how DiffView is designed to work - it's designed to work with the VCS provider to work out changes - for example it relies on having the diff rather than the 2 files etc.

So, perhaps a simple "compare 2 files" plugin might be what you want.  Alternatively, I'd be very happy to accept a pull request for P4 support - see e5e2280c00ffbc855914cb4b0b9d85f79d8b10a1 for the pull changes required for somebody to add bazaar support...
